# Generated by Django 5.0.4 on 2024-05-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('GOLD', 'Gold')], default='BASIC', max_length=20),
        ),
    ]
