# Generated by Django 5.0.4 on 2024-05-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userprofile_plan_delete_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('Free', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('GOLD', 'Gold')], default='Free', max_length=20),
        ),
    ]
