# Generated by Django 5.0.4 on 2024-05-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
