# Generated by Django 5.0.4 on 2024-05-29 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_panier_product_panier_quantity_panier_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='location',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='commande',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='phone_number',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='commande_number',
            field=models.CharField(default='gyRx04PExM', max_length=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.panier'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
