# Generated by Django 5.0.4 on 2024-05-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_commande_location_commande_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande_number',
            field=models.CharField(default='GjWio7wpUn', max_length=10),
        ),
    ]
