# Generated by Django 5.0.4 on 2024-05-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_commande_commande_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande_number',
            field=models.CharField(default='2bJ0SRlh6e', max_length=10),
        ),
    ]
