# Generated by Django 5.0.4 on 2024-05-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_commande_panier_commande_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande_number',
            field=models.CharField(default='E2yJPOFSND', max_length=10),
        ),
    ]
