# Generated by Django 5.0.4 on 2024-05-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_partners_alter_commande_commande_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande_number',
            field=models.CharField(default='PrPWuORX3E', max_length=10),
        ),
    ]
