# Generated by Django 5.0.4 on 2024-06-02 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_commande_commande_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande_number',
            field=models.CharField(default='FMX1lGP5IF', max_length=10),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='unknown', max_length=20)),
                ('location', models.CharField(default='unknown', max_length=255)),
                ('firstname', models.CharField(default='unknown', max_length=20)),
                ('lastname', models.CharField(default='unknown', max_length=20)),
                ('age', models.PositiveIntegerField(default=0)),
                ('job', models.CharField(default='unknown', max_length=20)),
                ('avatar', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
