# Generated by Django 5.0.4 on 2024-06-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_commande_commande_number_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande_number',
            field=models.CharField(default='gMhrWmG2a5', max_length=10),
        ),
    ]
