# Generated by Django 5.0.4 on 2024-06-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_commande_commande_number_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande_number',
            field=models.CharField(default='CQzcHEIS5p', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(default='Free', max_length=20),
        ),
    ]
