# Generated by Django 5.0.4 on 2024-06-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_commande_commande_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='state',
        ),
        migrations.AlterField(
            model_name='commande',
            name='commande_number',
            field=models.CharField(default='lDVEeMiMAN', max_length=10),
        ),
    ]
